### ISSUE TITLE
大佬能打包成exe吗?

### ISSUE THREAD

**Issue by Ashasdk** [wjkcxs/Fucking#1]
星拉已经

**Comment by wjkcxs** [comment]
试一下，等上完网课再说...վ'ᴗ' ի
况且我也不是大佬

**Comment by wjkcxs** [comment]
我Python环境出问题了，要不你打包一个?

**Comment by Ashasdk** [comment]
> 我Python环境出问题了，要不你打包一个?

我不会呀QAQ

**Comment by wjkcxs** [comment]
✔已经配置好了,你可以 _阅读文档_ ,并获知他的使用方法.祝你玩的愉快!
